### PR TITLE
added takeFirst and takeFirst_n

### PR DESCRIPTION
**Pull request by almostintuitive**
Hi,

First I have to say, I'm really happy that this library exists, thanks for all the work that went into it!

I've expanded it slightly by adding two functions that I was desperately in a need for - takeFirst and takeFirst_n.

I'm aware that my terminology is confusing, but I haven't yet found an equivalent in any functional libraries or Haskell.

Before merging in, I'd definitely like to ask the maintainers and whoever is reading this: what would be the best name for this operation?

Also, I've only added them to LazyCollectionType so far. I'm happy to make it available on eager Collections/Sequences if somebody would find it useful (or just for the sake of consistency).

I've included tests for the added functionality.

Thanks!

### CODE REVIEW

**Comment by oisdk** [comment]
Thanks for the pull request! As it happens, the `takeFirst` method already exists: it's called [`first`](https://github.com/oisdk/SwiftSequence/blob/master/Sources/Finding.swift#L11). The `takeFirst_n` is achievable with `filter` and `prefix`:

``` swift
(0..<10) // [0, 2, 4, 6]
  .filter { $0 % 2 == 0 }
  .prefix(4)
```

Although `prefix` isn't lazy in its current form. I'm not sure about putting `filter` and `prefix` things into one method: it doesn't seem very composable. I think maybe a lazy `prefix` is preferable, which would let you do something like this:

``` swift
(0..<10) // [0, 2, 4, 6]
  .lazy
  .filter { $0 % 2 == 0 }
  .prefix(4)
```

**Comment by almostintuitive** [comment]
Thanks for the response!

You're right, it would be a lot nicer to do lazy.filter.prefix instead of this. My original problem was the one you pointed out -  prefix doesn't have a lazy variant, it's performed eagerly even on lazy lists, which kind of defeats the point!

Now that I think about it again (writing a lazy prefix was the original idea, but I wasn't that familiar with writing lazy generators, and writing this seemed more easy), it may be possible to do it though, based on this and and your implementation of various generators.

I'll do some work on this and submit another PR!

Ohh just one thing - not that it matters much, but first(predicate) wasn't previously defined for lazy collections. Is this a useful addition? Or should I strip it and restrict this PR to add a lazy prefix(x) ?

Thanks for the feedback!

**Comment by oisdk** [comment]
I'm not sure how a lazy `first(predicate)` would work. How would it be different from an eager version?

**Comment by almostintuitive** [comment]
It wouldn't be any different in terms of API, and underneath, it would just use filter(predicate).lazyPrefix(1).

The reason why I'm bringing it up since as of the last commit in master, .first is not defined on LazySequenceType, only on SequenceType. Not sure if it'll be super useful, but may be a worthy addition - at least I had a case when I wanted to use it:).

**Comment by oisdk** [comment]
Yes, but `LazySequenceType

**Comment by oisdk** [comment]
Yes, but `LazySequenceType` inherits from `SequenceType`, so on any lazy sequence, you already have the `first` method. I'm not sure, but I don't think that a lazy version of `first` would function any differently than the eager version of `first` (since both have to evaluate the sequence up until the first thing that passes the predicate, and neither would evaluate the rest)

**Comment by almostintuitive** [comment]
True! I was really confused by the the fact that when I was in the framework project  in other files, autocomplete wasn't offering me first on any LazySequenceTypes...

Let me close this and thank you!:)

**Pull request closed without merging**
